version: '3.2'

services:
  influxdb:
    build: influxdb
    restart: on-failure
    env_file: configuration.env
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    build: grafana
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
#      - grafana_data:/etc/grafana
#      - grafana_data:/var/log/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}